name: CD - Deploy functions

on:
  push:
    branches: 
      - 'release/**'
      - 'main'
    paths:
      - '.github/workflows/deploy-functions.yml'
      - 'functions/**'

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: git-clone
        name: Cloning repository

      - uses: docker/login-action@v1
        name: Docker hub login
        id: docker-hub-login
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSOWRD }}

      - uses: docker/build-push-action@v2
        name: Build and push image
        id: build-and-push
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_IMAGE_TAG }}
